[phases.build]
cmds = [
    "rm -rf node_modules/.cache",
    "rm -rf .npm",
    "npm cache clean --force",
    "npm install --frozen-lockfile --no-optional --no-fund",
    "npm run build"
]

[phases.start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
